### ISSUE TITLE
other classes schedule 

### ISSUE THREAD

**Issue by Simple-MAX** [Blatzar/schoolsoft-api#1]
This is not an issue but I was wondering if it's possible to get other classes schedule?

**Comment by Blatzar** [comment]
Possible? Probably, but not without code modifications. The sceduling wasn't done with multiple lessons at the same time, so it'd probably break. This repo is deprecated in favor of schoolsoft-api-app, in which I will investigate class scheduling.

**Comment by Blatzar** [comment]
Doesn't seem like it's possible to get other classes schedule using the app api, I'll have to rework this repo.

**Comment by Blatzar** [comment]
@Simple-MAX check https://github.com/Blatzar/schoolsoft-api/blob/dev/schoolsoft.py I'm merging it once I've reworked all code. That should be able to schedule from different classes, change https://github.com/Blatzar/schoolsoft-api/blob/dev/schoolsoft.py#L216 accordingly to the ID of the class you want to get, will add a flag soon:tm:
![image](https://user-images.githubusercontent.com/46196380/96789701-eb44c500-13f5-11eb-9ce2-346c2c97fe2d.png)

**Comment by Blatzar** [comment]
Now fully supported, use 
```python3
api.fetch_schedule(requestid=id)
```
